version: "3.9"

services:

  app:
    container_name: rates_app
    build: .
    volumes:
      - .:/code
    ports:
      - 8080:8080
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@rates_db:5432/postgres
      - DATABASE_TEST_URL=postgres://postgres:postgres@rates_db:5432/postgres

  db:
    container_name: rates_db
    build:
      dockerfile: psql.Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
